
include-file = ~/.config/polybar/colors1.ini

[bar/example]
monitor = HDMI-0
width = 98%
height = 25pt

offset-x = 1%
offset-y = 8

radius = 14

; dpi = 96

background = #991A1F27
foreground = ${colors.foreground}

line-size = 2pt

border-size = 0
border-color = #00000000

padding-left = 2
padding-right = 2

module-margin = 2

separator = |
separator-foreground = ${colors.orange}

font-0 = "JetBrainsMono Nerd Font:size=11;1"
font-1 = "Font Awesome 7 Brands:size=10;2"
font-2 = "Font Awesome 7 Free Solid:size=10;2"
font-3 = "JetBrains Mono:size=10;0"

modules-left = bspwm xwindow
modules-center = cpu memory gpu temp
modules-right = wlan bluetooth pulseaudio date battery powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
enable-click = true
enable-scroll = true

label-focused = %icon%
label-focused-foreground = ${colors.blue}
label-focused-background = ${colors.background-alt}
#label-focused-underline = #89b4fa
label-focused-padding = 2

label-occupied = %icon%
label-occupied-background = #991A1F27
label-occupied-foreground = ${colors.green}
label-occupied-padding = 2

label-empty = %icon%
label-empty-foreground = ${colors.blacker}
label-empty-padding = 2

label-urgent = %icon%
label-urgent-foreground = #f38ba8
label-urgent-background = ${colors.background-alt}
label-urgent-padding = 2

strip-wsnumbers = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-foreground = ${colors.pink}

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = custom/script
exec = ~/.config/polybar/scripts/volume.sh
interval = 1
click-left = ~/.config/polybar/scripts/volume-mute.sh
scroll-up = ~/.config/polybar/scripts/volume-up.sh
scroll-down = ~/.config/polybar/scripts/volume-down.sh
label = %output% 

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.primary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format = <label>
format-prefix = "󰑹 "
label = %percentage_used%%
format-prefix-foreground = ${colors.green}
label-foreground = ${colors.foreground}

[module/cpu]
type = internal/cpu
interval = 2
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.teal}
label-foreground = ${colors.foreground}
label = %percentage%%

[network-base]
type = internal/network
interval = 5
format-connected = %{A1:~/.config/rofi/scripts/network-menu:}<label-connected>%{A}
format-disconnected = %{A1:~/.config/rofi/scripts/network-menu:}<label-disconnected>%{A}
label-disconnected = 󰤭 Offline
label-disconnected-foreground = ${colors.disabled}

[module/wlan]
type = custom/script
exec = ~/.config/polybar/scripts/wifi-status
interval = 5
click-left = ~/.config/rofi/scripts/network-menu
format = <label>
label = %output%

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth-status
interval = 5
click-left = ~/.config/rofi/scripts/bluetooth-menu
format = <label>
label = %output%

[module/eth]
inherit = network-base
interface-type = wireless
label-connected = 󰈀 %ifname%
label-connected-foreground = ${colors.foreground}

[module/date]
type = internal/date
interval = 60
date = %I:%M %p
date-alt = %Y-%m-%d %H:%M:%S
format = <label>
format-prefix = "  "
format-prefix-foreground = ${colors.yellow}
label = %date%
label-foreground = ${colors.foreground}

[module/powermenu]
type = custom/text
content = ⏻
content-foreground = ${colors.teal}
click-left = ~/.config/polybar/scripts/powermenu.sh

[module/gpu]
type = custom/script
exec = nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits | awk '{print $1"%"}'
interval = 2
format = <label>
format-prefix = "󰢮 "
format-prefix-foreground = ${colors.yellow}
label = %output%
label-foreground = ${colors.foreground}

[module/temp]
type = custom/script
exec = sensors | awk '/Package id 0:/ {print " "$4; exit}'
interval = 5

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
poll-interval = 5
format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>
label-charging = 󰂄 %percentage%%
label-discharging = 󰁹 %percentage%%
label-full = 󰁹 100%

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
